// Published facilities around the demo origin, not invented clinics.
// Maina et al., Scientific Data (2019): public and other health facilities in
// sub-Saharan Africa. This slice is Kenya, within 25 km of lat -0.42, lon 36.95
// (Nyeri; the brief's Ondera highlands). HDX dataset
// health-facilities-in-sub-saharan-africa, CC BY. The table has a name, a type,
// and coordinates. It does not say which IMCI services a facility offers, so
// services stays empty and the matcher must not treat a place as able to provide care.
//
// healthsites.io/OpenStreetMap was not used for this list. Near this point the
// OSM export tags a morgue as a hospital and still has no service flags.

import type { Facility } from "../types";

export const DEMO_ORIGIN = { lat: -0.42, lon: 36.95 };

export const FACILITY_SOURCE = "Maina et al., Scientific Data (2019), via HDX health-facilities-in-sub-saharan-africa (CC BY). No IMCI services in the source.";

// maina-001 is the closest to DEMO_ORIGIN. Ids stay short so the handoff can store them.

export const DEMO_FACILITIES: Facility[] = [
  {
    id: "maina-001",
    name: "Good Samaritan ACK Medical Clinic",
    lat: -0.4197,
    lon: 36.9495,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-002",
    name: "Nyeri Town Health Centre",
    lat: -0.4198,
    lon: 36.9491,
    level: "health_centre",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-003",
    name: "Tumaini ACK Clinic",
    lat: -0.4208,
    lon: 36.9544,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-004",
    name: "Nyeri Islamic Foundation Clinic",
    lat: -0.4223,
    lon: 36.9552,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-005",
    name: "Kenwa-Nyeri Clinic",
    lat: -0.4263,
    lon: 36.9406,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-006",
    name: "Nyeri Provincial General Hospital",
    lat: -0.424,
    lon: 36.9611,
    level: "district_hospital",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-007",
    name: "Pcea Nyeri Hill Women Guild Dispensary",
    lat: -0.4108,
    lon: 36.9577,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-008",
    name: "Mt Kenya Sub-District Hospital",
    lat: -0.4241,
    lon: 36.9341,
    level: "district_hospital",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-009",
    name: "Consolata Mission Hospital",
    lat: -0.4138,
    lon: 36.9197,
    level: "district_hospital",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-010",
    name: "Kamuyu Dispensary",
    lat: -0.4261,
    lon: 36.9196,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-011",
    name: "Sacred Heart Mission Dispensary",
    lat: -0.4386,
    lon: 36.9121,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-012",
    name: "Sugarbaker Memorial Clinic",
    lat: -0.4488,
    lon: 36.992,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-013",
    name: "Nyaribo Dispensary",
    lat: -0.3789,
    lon: 36.983,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-014",
    name: "Kihuyo Dispensary",
    lat: -0.3823,
    lon: 36.9118,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-015",
    name: "Kiandere Dispensary",
    lat: -0.4541,
    lon: 36.9076,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-016",
    name: "Wamagana Health Centre",
    lat: -0.4735,
    lon: 36.929,
    level: "health_centre",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-017",
    name: "Kagioini Catholic Dispensary",
    lat: -0.4754,
    lon: 36.931,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-018",
    name: "Ihururu Health Centre",
    lat: -0.4092,
    lon: 36.8922,
    level: "health_centre",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-019",
    name: "Gatitu GOK Dispensary",
    lat: -0.4593,
    lon: 36.9969,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-020",
    name: "Kiganjo Health Centre",
    lat: -0.3813,
    lon: 37.0027,
    level: "health_centre",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-021",
    name: "Karia Health Centre",
    lat: -0.4689,
    lon: 36.9939,
    level: "health_centre",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-022",
    name: "Kinunga Health Centre",
    lat: -0.436,
    lon: 36.8859,
    level: "health_centre",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-023",
    name: "Kanjora PCEA Dispensary",
    lat: -0.4087,
    lon: 36.8797,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-024",
    name: "St John Catholic Dispensary",
    lat: -0.343,
    lon: 36.9686,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-025",
    name: "Gachika Orthodox Medical Clinic",
    lat: -0.4318,
    lon: 37.0285,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-026",
    name: "Little Flower Dispensary",
    lat: -0.4318,
    lon: 37.0285,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-027",
    name: "Mathakwaini PCEA Dispensary",
    lat: -0.4946,
    lon: 36.9228,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-028",
    name: "Gatei Dispensary",
    lat: -0.3926,
    lon: 37.0251,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-029",
    name: "Wandumbi Dispensary",
    lat: -0.4675,
    lon: 36.8807,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-030",
    name: "Njoguini Dispensary",
    lat: -0.4034,
    lon: 36.8673,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-031",
    name: "Kagere Dispensary",
    lat: -0.5046,
    lon: 36.9456,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-032",
    name: "Honi PCEA Dispensary",
    lat: -0.3458,
    lon: 36.993,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-033",
    name: "Gichira Health Centre",
    lat: -0.4713,
    lon: 37.0195,
    level: "health_centre",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-034",
    name: "Kahiga Dispensary",
    lat: -0.4096,
    lon: 36.8614,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-035",
    name: "St Michael Dispensary",
    lat: -0.4966,
    lon: 36.9965,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-036",
    name: "Ichagachiru Dispensary",
    lat: -0.4482,
    lon: 36.8643,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-037",
    name: "Ndugamano Dispensary",
    lat: -0.4908,
    lon: 36.8906,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-038",
    name: "Kids Alive Dispensary",
    lat: -0.371,
    lon: 37.0316,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-039",
    name: "Muruguru Dispensary",
    lat: -0.4637,
    lon: 37.0365,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-040",
    name: "Kirurumi Dispensary",
    lat: -0.4395,
    lon: 36.8544,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-041",
    name: "Kamoko Health Centre",
    lat: -0.5097,
    lon: 36.9115,
    level: "health_centre",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-042",
    name: "St Monica Dispensary",
    lat: -0.5144,
    lon: 36.9764,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-043",
    name: "Mahiga PCEA Dispensary",
    lat: -0.5158,
    lon: 36.9259,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-044",
    name: "Mary Immaculate Hospital",
    lat: -0.3305,
    lon: 36.9045,
    level: "district_hospital",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-045",
    name: "Marua Dispensary",
    lat: -0.4518,
    lon: 37.0463,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-046",
    name: "Zaina Dispensary",
    lat: -0.429,
    lon: 36.8489,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-047",
    name: "Karima Dispensary",
    lat: -0.5194,
    lon: 36.9799,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-048",
    name: "Kagonye Dispensary",
    lat: -0.5119,
    lon: 36.9014,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-049",
    name: "Karima Catholic Dispensary",
    lat: -0.5217,
    lon: 36.9789,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-050",
    name: "St Joseph Brothers Dispensary",
    lat: -0.3177,
    lon: 36.9132,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-051",
    name: "Ngurumo Dispensary",
    lat: -0.4597,
    lon: 37.0527,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-052",
    name: "Gatugi Mission Dispensary",
    lat: -0.5329,
    lon: 36.9605,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-053",
    name: "Hubuini Dispensary",
    lat: -0.4868,
    lon: 36.8572,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-054",
    name: "Amboni Dispensary",
    lat: -0.3357,
    lon: 36.8721,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-055",
    name: "Mweiga Health Centre",
    lat: -0.3176,
    lon: 36.8899,
    level: "health_centre",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-056",
    name: "Munyange Gikoe Dispensary",
    lat: -0.5041,
    lon: 36.8657,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-057",
    name: "Munyange AIPCA Dispensary",
    lat: -0.5042,
    lon: 36.8656,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-058",
    name: "Othaya Sub-District Hospital",
    lat: -0.5399,
    lon: 36.94,
    level: "district_hospital",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-059",
    name: "Thung'ari Dispensary",
    lat: -0.3111,
    lon: 37.0035,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-060",
    name: "Gitugi Dispensary",
    lat: -0.5129,
    lon: 36.8715,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-061",
    name: "Kairuthi Dispensary",
    lat: -0.5293,
    lon: 36.8929,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-062",
    name: "Ngorano Health Centre",
    lat: -0.4125,
    lon: 37.0734,
    level: "health_centre",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-063",
    name: "Tambaya Dispensary",
    lat: -0.5251,
    lon: 37.0182,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-064",
    name: "St Anne's Cry For The World Clinic",
    lat: -0.4962,
    lon: 37.0507,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-065",
    name: "Wakamata Dispensary",
    lat: -0.4999,
    lon: 37.0507,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-066",
    name: "Othaya Catholic Dispensary",
    lat: -0.5505,
    lon: 36.9448,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-067",
    name: "Thageini Dispensary",
    lat: -0.5092,
    lon: 37.0466,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-068",
    name: "Witima Health Centre",
    lat: -0.5493,
    lon: 36.9781,
    level: "health_centre",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-069",
    name: "Ningaini Dispensary",
    lat: -0.5265,
    lon: 37.0298,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-070",
    name: "Witima Catholic Dispensary",
    lat: -0.5528,
    lon: 36.9782,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-071",
    name: "Wendiga Dispensary",
    lat: -0.3135,
    lon: 36.8651,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-072",
    name: "Ruguru Community Health Centre",
    lat: -0.3851,
    lon: 37.0835,
    level: "health_centre",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-073",
    name: "Gatura PCEA Dispensary",
    lat: -0.5283,
    lon: 37.0397,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-074",
    name: "Aguthi Dispensary",
    lat: -0.5419,
    lon: 37.024,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-075",
    name: "Tumutumu PCEA Hospital",
    lat: -0.4855,
    lon: 37.0795,
    level: "district_hospital",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-076",
    name: "Ngandu Catholic Dispensary",
    lat: -0.457,
    lon: 37.0921,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-077",
    name: "Ihuririo Dispensary",
    lat: -0.5478,
    lon: 36.8687,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-078",
    name: "Kabebero AIPCA Dispensary",
    lat: -0.5478,
    lon: 36.8687,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-079",
    name: "Kiamuya Dispensary",
    lat: -0.5726,
    lon: 36.9583,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-080",
    name: "Gitundu ACK Dispensary",
    lat: -0.5701,
    lon: 36.9173,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-081",
    name: "Njoki Dispensary",
    lat: -0.5654,
    lon: 37.0002,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-082",
    name: "Gichiche Health Centre",
    lat: -0.5756,
    lon: 36.9243,
    level: "health_centre",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-083",
    name: "Ruruguti Dispensary",
    lat: -0.5676,
    lon: 36.8937,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-084",
    name: "Itiati Dispensary",
    lat: -0.4134,
    lon: 37.1097,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-085",
    name: "Unjiru Health Centre",
    lat: -0.4521,
    lon: 37.1109,
    level: "health_centre",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-086",
    name: "Kihuri Dispensary",
    lat: -0.5592,
    lon: 36.8594,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-087",
    name: "Mbiriri Catholic Dispensary",
    lat: -0.3183,
    lon: 37.0827,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-088",
    name: "Mukurweini District Hospital",
    lat: -0.5592,
    lon: 37.0446,
    level: "district_hospital",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-089",
    name: "Mukurweini St Veronica Dispensary",
    lat: -0.5554,
    lon: 37.0522,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-090",
    name: "Kiaguthu Dispensary",
    lat: -0.5913,
    lon: 36.9506,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-091",
    name: "Kariko Dispensary",
    lat: -0.5767,
    lon: 36.8806,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-092",
    name: "Wahundura Dispensary",
    lat: -0.5883,
    lon: 36.9901,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-093",
    name: "Solio Dispensary",
    lat: -0.2462,
    lon: 36.9484,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-094",
    name: "Magutu PCEA Dispensary",
    lat: -0.4088,
    lon: 37.1236,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-095",
    name: "Ichamara Dispensary",
    lat: -0.5426,
    lon: 37.0788,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-096",
    name: "Gitimaini Dispensary",
    lat: -0.4086,
    lon: 37.1275,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-097",
    name: "Kiria-Ini Dispensary",
    lat: -0.5994,
    lon: 36.9516,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-098",
    name: "Gathethu Dispensary",
    lat: -0.4142,
    lon: 37.1297,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-099",
    name: "Nyakahuho Dispensary",
    lat: -0.5851,
    lon: 37.0229,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-100",
    name: "Karatina Catholic Dispensary",
    lat: -0.479,
    lon: 37.1214,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-101",
    name: "Kiria-Ini Mission Hospital",
    lat: -0.6025,
    lon: 36.953,
    level: "district_hospital",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-102",
    name: "Gitunduti Catholic Dispensary",
    lat: -0.3913,
    lon: 37.1323,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-103",
    name: "Kagicha Dispensary",
    lat: -0.6003,
    lon: 36.9019,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-104",
    name: "Karatina District Hospital",
    lat: -0.4758,
    lon: 37.1302,
    level: "district_hospital",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-105",
    name: "Kihuro ACK Dispensary",
    lat: -0.608,
    lon: 36.9691,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-106",
    name: "Kamacharia Dispensary",
    lat: -0.6046,
    lon: 36.9925,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-107",
    name: "Kaiyaba Dispensary",
    lat: -0.4953,
    lon: 37.1246,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-108",
    name: "Iruri Dispensary",
    lat: -0.5914,
    lon: 37.0327,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-109",
    name: "St Luke Kihuro ACK Dispensary",
    lat: -0.61,
    lon: 36.97,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-110",
    name: "Endarasha Rural Health Centre",
    lat: -0.3079,
    lon: 36.7941,
    level: "health_centre",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-111",
    name: "Kiamabara Dispensary",
    lat: -0.5177,
    lon: 37.1161,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-112",
    name: "Karatina Home Based Care Dispensary",
    lat: -0.473,
    lon: 37.1354,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-113",
    name: "Ngaru Dispensary",
    lat: -0.5949,
    lon: 36.8652,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-114",
    name: "Kiarithaini Dispensary",
    lat: -0.462,
    lon: 37.141,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-115",
    name: "Mihuti Dispensary",
    lat: -0.5658,
    lon: 37.0807,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-116",
    name: "Karindundu Dispensary",
    lat: -0.4934,
    lon: 37.1318,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-117",
    name: "Rau Dispensary",
    lat: -0.6097,
    lon: 37.0057,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-118",
    name: "Kanjama Dispensary",
    lat: -0.6187,
    lon: 36.9503,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-119",
    name: "Ihwagi Dispensary",
    lat: -0.4445,
    lon: 37.1474,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-120",
    name: "Iruri Dispensary",
    lat: -0.6014,
    lon: 37.0332,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-121",
    name: "Kagumoini Dispensary",
    lat: -0.618,
    lon: 36.9805,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-122",
    name: "Kiambuthia Dispensary",
    lat: -0.6184,
    lon: 36.9095,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-123",
    name: "Muthuthiini Dispensary",
    lat: -0.5943,
    lon: 37.0558,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-124",
    name: "Kairo Dispensary",
    lat: -0.6089,
    lon: 36.8722,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-125",
    name: "Kihuti Orthodox Clinic",
    lat: -0.556,
    lon: 37.1033,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-126",
    name: "Kabati Dispensary",
    lat: -0.2548,
    lon: 36.8259,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-127",
    name: "Island Farms Dispensary",
    lat: -0.2927,
    lon: 37.114,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-128",
    name: "Ndathi Dispensary",
    lat: -0.2988,
    lon: 37.1191,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-129",
    name: "Kahaaro Dispensary",
    lat: -0.5923,
    lon: 37.0678,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-130",
    name: "Karundu Dispensary",
    lat: -0.574,
    lon: 37.093,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-131",
    name: "Giakaibei Catholic Dispensary",
    lat: -0.4127,
    lon: 37.1605,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-132",
    name: "Kahuru Dispensary",
    lat: -0.4569,
    lon: 37.1609,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-133",
    name: "Gikoe Dispensary",
    lat: -0.6339,
    lon: 36.9282,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-134",
    name: "Prisca Wakarima ACK Dispensary",
    lat: -0.626,
    lon: 37.0124,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-135",
    name: "Gatondo Dispensary",
    lat: -0.4324,
    lon: 37.1655,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-136",
    name: "Ndimaini Dispensary",
    lat: -0.527,
    lon: 37.1386,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-137",
    name: "Igana Dispensary",
    lat: -0.5851,
    lon: 37.0937,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-138",
    name: "Gakurwe Dispensary",
    lat: -0.6263,
    lon: 37.0247,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-139",
    name: "Nyakianga Health Centre",
    lat: -0.6394,
    lon: 36.9575,
    level: "health_centre",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-140",
    name: "Mutira ACK Dispensary",
    lat: -0.4896,
    lon: 37.1588,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-141",
    name: "Gacharageini Dispensary",
    lat: -0.6298,
    lon: 36.879,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
  {
    id: "maina-142",
    name: "Warazo Jet Catholic Dispensary",
    lat: -0.2646,
    lon: 37.1109,
    level: "health_post",
    services: [],
    source: FACILITY_SOURCE,
  },
];
